import { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

type Module = 'dashboard'|'upload'|'variables'|'quality'|'descriptive'|'table1'|'association'|'regression'|'diagnostic'|'roc'|'graphs'|'results'
type Info = { filename?: string; rows:number; columns:number; variables:Array<Record<string,unknown>> }
type ApiResponse = Record<string, any>
const API='https://medical-data-analysis-api.onrender.com'
const modules:[Module,string,string][]=[['dashboard','Dashboard','⌂'],['upload','Data Upload','↑'],['variables','Variable View','☷'],['quality','Data Quality','✓'],['descriptive','Descriptive','▤'],['table1','Table 1','▥'],['association','Association','↔'],['regression','Regression','β'],['diagnostic','Diagnostic','⊕'],['roc','ROC Analysis','⌁'],['graphs','Graphs','◒'],['results','Results & Export','↓']]
const ACCEPT='.csv,.xlsx,.xls,.xlsm,.dta,.tsv,.ods,.sav,.sas7bdat,.json,.txt,.doc,.docx,.pdf,.rtf'
const SUPPORTED='Excel (XLSX, XLS, XLSM), CSV, TSV, Stata DTA, ODS, SPSS SAV, SAS, JSON, TXT, DOC/DOCX, PDF, RTF'

function App(){
 const [active,setActive]=useState<Module>('dashboard'),[file,setFile]=useState<File|null>(null),[info,setInfo]=useState<Info|null>(null),[quality,setQuality]=useState<any>(null),[result,setResult]=useState<ApiResponse|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('Upload a dataset to begin'),[apiStatus,setApiStatus]=useState<'ok'|'error'|'checking'>('checking')
 useEffect(()=>{fetch(`${API}/health`).then(r=>{if(!r.ok)throw Error();setApiStatus('ok')}).catch(()=>setApiStatus('error'))},[])
 const variables=useMemo(()=>info?.variables.map(v=>String(v.name))||[],[info])
 async function post(path:string,fields:Record<string,string>={}){if(!file)throw Error('Please upload a dataset first.');const f=new FormData();f.append('file',file);Object.entries(fields).forEach(([k,v])=>f.append(k,v));const r=await fetch(`${API}${path}`,{method:'POST',body:f});const text=await r.text();if(!r.ok)throw Error(text||`Request failed (${r.status})`);return JSON.parse(text)}
 async function loadDataset(next:File){setFile(next);setBusy(true);setMessage('Reading dataset and checking quality…');try{const f=new FormData();f.append('file',next);const r=await fetch(`${API}/api/v1/data/inspect`,{method:'POST',body:f});if(!r.ok)throw Error(await r.text());const i=await r.json();setInfo(i);const qf=new FormData();qf.append('file',next);const q=await fetch(`${API}/api/v1/data/quality`,{method:'POST',body:qf});setQuality(q.ok?(await q.json()).results:null);setResult(null);setMessage('Dataset is ready for analysis');setActive('dashboard')}catch(e){setMessage(e instanceof Error?e.message:'Upload failed')}finally{setBusy(false)}}
 async function run(path:string,fields:Record<string,string>){setBusy(true);setMessage('Running analysis…');try{setResult(await post(path,fields));setActive('results');setMessage('Analysis completed successfully')}catch(e){setResult({error:e instanceof Error?e.message:'Analysis failed'});setActive('results');setMessage('Analysis failed — review the message below')}finally{setBusy(false)}}
 return <div className="app"><aside className="sidebar"><div className="brand"><div className="brand-mark">M</div><div><strong>Medical Analytics</strong><span>Research statistics platform</span></div></div><div className="side-section">WORKSPACE</div><nav>{modules.map(([id,label,icon])=><button key={id} className={active===id?'active':''} onClick={()=>setActive(id)}><i>{icon}</i><span>{label}</span></button>)}</nav><div className="side-footer"><span className={`dot ${apiStatus==='error'?'bad':''}`}/>{apiStatus==='ok'?'Analysis engine online':apiStatus==='error'?'Analysis engine offline':'Connecting…'}<small>Python statistical engine</small></div></aside>
 <main className="main"><header><div><span className="eyebrow">Clinical research workspace</span><h1>{modules.find(x=>x[0]===active)?.[1]}</h1><p>{file?`${file.name}  ·  ${info?.rows??'—'} records  ·  ${info?.columns??'—'} variables`:'A clean workflow for medical data analysis'}</p></div><label className="top-upload">+ Upload files<input hidden type="file" multiple accept={ACCEPT} onChange={e=>e.target.files?.[0]&&loadDataset(e.target.files[0])}/></label></header>
 <div className={`statusbar ${apiStatus}`}><span className="status-dot"/><b>{apiStatus==='ok'?'Engine ready':apiStatus==='error'?'Engine unavailable':'Checking engine'}</b><span>{message}</span></div>
 {active==='dashboard'&&<Dashboard info={info} busy={busy} onUpload={()=>setActive('upload')} onRun={()=>setActive('descriptive')} onModule={setActive}/>} 
 {active==='upload'&&<Upload file={file} busy={busy} onUpload={loadDataset}/>} 
 {active==='variables'&&<Panel title="Variable View" subtitle="Understand every variable before selecting an analysis.">{info?<VariableTable variables={info.variables}/>:<Empty icon="☷" title="No dataset loaded" text="Upload a CSV, Excel, Stata or other supported file to inspect variables."/>}</Panel>}
 {active==='quality'&&<Quality data={quality}/>} 
 {active==='descriptive'&&<VariablePicker title="Descriptive Statistics" variables={variables} hint="Choose one or more variables." action="Run descriptive analysis" busy={busy} onRun={v=>v.length?run('/api/v1/analysis/descriptive',{variables:v.join(',')}):setMessage('Select at least one variable before running the analysis')}/>} 
 {active==='table1'&&<TableOne variables={variables} busy={busy} onRun={(v)=>v.variables.length?run('/api/v1/analysis/table-one',{variables:v.variables.join(','),group:v.group}):setMessage('Select at least one variable for Table 1')}/>} 
 {active==='association'&&<PairAnalysis title="Categorical Association" subtitle="Compare two categorical variables using chi-square / Fisher exact." a="Exposure / variable" b="Outcome" variables={variables} busy={busy} onRun={v=>run('/api/v1/analysis/association',{variable:v.a,outcome:v.b})}/>} 
 {active==='diagnostic'&&<PairAnalysis title="Diagnostic Accuracy" subtitle="Compare an index test against the reference standard." a="Index test" b="Reference standard" variables={variables} busy={busy} onRun={v=>run('/api/v1/analysis/diagnostic',{index_test:v.a,reference_standard:v.b})}/>} 
 {active==='roc'&&<PairAnalysis title="ROC Analysis" subtitle="Evaluate discrimination and identify the Youden-optimal threshold." a="Test / predictor" b="Binary outcome" variables={variables} busy={busy} onRun={v=>run('/api/v1/analysis/roc',{test:v.a,outcome:v.b})}/>} 
 {active==='regression'&&<Regression variables={variables} busy={busy} onRun={(path,c)=>run(path,{config:JSON.stringify(c)})}/>} 
 {active==='graphs'&&<Panel title="Publication-ready graphs" subtitle="The graph workspace is reserved for validated clinical visualizations."><Empty icon="◒" title="Graph workspace" text="Charts will be generated from selected analysis results rather than raw code output."/></Panel>}
 {active==='results'&&<Results result={result}/>}</main></div>
}

function Dashboard({info,busy,onUpload,onRun,onModule}:{info:Info|null;busy:boolean;onUpload:()=>void;onRun:()=>void;onModule:(m:Module)=>void}){return <div className="dashboard"><section className="hero-new"><div className="hero-copy"><div className="hero-badge"><span/> MEDICAL DATA ANALYSIS</div><h2>From raw dataset to <em>research-ready</em> results.</h2><p>Upload clinical files, inspect variables, choose an analysis visually, and get clean statistical tables.</p><div className="hero-actions"><button className="primary" onClick={onUpload}>Upload files <span>→</span></button>{info&&<button className="ghost" onClick={onRun}>Start analysis</button>}</div><div className="trust-row"><span>✓ Excel</span><span>✓ CSV</span><span>✓ Stata</span><span>✓ Documents</span></div></div><div className="hero-visual"><div className="visual-window"><div className="window-top"><span/><span/><span/><b>Analysis workspace</b></div><div className="mini-chart"><div className="chart-bars"><i style={{height:'42%'}}/><i style={{height:'68%'}}/><i style={{height:'54%'}}/><i style={{height:'86%'}}/><i style={{height:'63%'}}/></div><div className="chart-line"><span>RR</span><b>1.42</b><small>95% CI 1.08–1.87</small></div></div><div className="mini-table"><span/><span/><span/><span/><span/><span/></div></div></div></section><div className="stat-grid"><Stat icon="◫" label="Dataset" value={info?.filename||'Not loaded'} /><Stat icon="#" label="Records" value={info?info.rows.toLocaleString():'—'}/><Stat icon="☷" label="Variables" value={info?String(info.columns):'—'}/><Stat icon="✓" label="Engine" value="Python / FastAPI"/></div><section className="section-block"><div className="section-heading"><div><span className="eyebrow">WORKFLOW</span><h3>Everything you need in one workspace</h3></div><span className="section-note">Built for medical research</span></div><div className="module-grid">{[['quality','Data Quality','Missing data, duplicates & consistency','✓'],['descriptive','Descriptive','Mean, SD, median & distributions','▤'],['table1','Table 1','Publication-style baseline table','▥'],['association','Association','Chi-square & Fisher exact','↔'],['regression','Regression','RR and OR models','β'],['diagnostic','Diagnostic','Sensitivity, specificity & CI','⊕']].map(([id,t,d,i])=><button className="module-card" key={id} onClick={()=>onModule(id as Module)}><span className="module-icon">{i}</span><div><b>{t}</b><small>{d}</small></div><strong>→</strong></button>)}</div></section><section className="bottom-callout"><div><span className="eyebrow">SUPPORTED INPUT</span><h3>Upload Excel, documents and data files</h3><p>{SUPPORTED}. Unsupported documents are retained for the project workflow but statistical analysis requires a readable dataset format.</p></div><button className="secondary" onClick={onUpload}>Open upload center</button></section></div>}
function Stat({icon,label,value}:{icon:string;label:string;value:string|number}){return <div className="stat-card"><span className="stat-icon">{icon}</span><div><small>{label}</small><b title={String(value)}>{value}</b></div></div>}
function Upload({file,busy,onUpload}:{file:File|null;busy:boolean;onUpload:(f:File)=>void}){return <Panel title="Upload Center" subtitle="Upload Excel, CSV, Stata, statistical data and document files. Multiple files are allowed for project preparation."><label className="drop"><div className="drop-icon">↑</div><b>{busy?'Processing dataset…':'Drop files here or click to browse'}</b><span>{SUPPORTED}</span><input type="file" multiple accept={ACCEPT} onChange={e=>{const f=e.target.files?.[0];if(f)onUpload(f)}}/></label>{file&&<div className="file-row"><span className="file-icon">✓</span><div><b>{file.name}</b><small>Selected for analysis</small></div><em>{(file.size/1024).toFixed(1)} KB</em></div>}<div className="upload-note"><b>Important:</b> DOC/DOCX/PDF files can be uploaded as reference documents, but statistical calculations require structured data such as XLSX, XLS, CSV, DTA, TSV, ODS, SAV or SAS.</div></Panel>}
function VariableTable({variables}:{variables:Array<Record<string,unknown>>}){return <div className="table-wrap"><table><thead><tr>{['Variable','Type','Storage','N','Missing','Unique','Min','Max'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{variables.map(v=><tr key={String(v.name)}><td><b>{String(v.name)}</b></td><td><span className="type-pill">{String(v.type)}</span></td><td>{String(v.storage_type)}</td><td>{String(v.n)}</td><td>{String(v.missing)}</td><td>{String(v.unique)}</td><td>{v.min==null?'—':String(v.min)}</td><td>{v.max==null?'—':String(v.max)}</td></tr>)}</tbody></table></div>}
function VariablePicker({title,variables,hint,action,busy,onRun}:{title:string;variables:string[];hint:string;action:string;busy:boolean;onRun:(v:string[])=>void}){const [selected,setSelected]=useState<string[]>([]);const all=variables.length>0&&selected.length===variables.length;const toggle=(v:string)=>setSelected(s=>s.includes(v)?s.filter(x=>x!==v):[...s,v]);return <Panel title={title} subtitle={hint}><SelectionToolbar count={selected.length} all={all} onAll={()=>setSelected(all?[]:variables)}/><div className="variable-grid">{variables.map(v=><button type="button" key={v} className={`variable-chip ${selected.includes(v)?'selected':''}`} onClick={()=>toggle(v)}><span className="check">{selected.includes(v)?'✓':''}</span><span>{v}</span></button>)}</div>{!variables.length&&<Empty icon="☷" title="No variables available" text="Upload a structured dataset before selecting variables."/>}<div className="action-row"><button className="primary" disabled={busy||!selected.length} onClick={()=>onRun(selected)}>{busy?'Running…':action}<span>→</span></button></div></Panel>}
function SelectionToolbar({count,all,onAll}:{count:number;all:boolean;onAll:()=>void}){return <div className="selection-toolbar"><div><b>{count}</b><span> variable{count===1?'':'s'} selected</span></div><button className="link" onClick={onAll}>{all?'Clear all':'Select all'}</button></div>}
function TableOne({variables,busy,onRun}:{variables:string[];busy:boolean;onRun:(v:{variables:string[];group:string})=>void}){const [selected,setSelected]=useState<string[]>([]),[group,setGroup]=useState('');const all=variables.length>0&&selected.length===variables.length;const toggle=(v:string)=>setSelected(s=>s.includes(v)?s.filter(x=>x!==v):[...s,v]);return <Panel title="Table 1" subtitle="Build a baseline characteristics table with an optional grouping variable."><SelectionToolbar count={selected.length} all={all} onAll={()=>setSelected(all?[]:variables)}/><div className="variable-grid">{variables.map(v=><button type="button" key={v} className={`variable-chip ${selected.includes(v)?'selected':''}`} onClick={()=>toggle(v)}><span className="check">{selected.includes(v)?'✓':''}</span>{v}</button>)}</div><div className="field"><span>Grouping variable <small>(optional)</small></span><select value={group} onChange={e=>setGroup(e.target.value)}><option value="">Overall only</option>{variables.map(v=><option key={v}>{v}</option>)}</select></div><button className="primary" disabled={busy||!selected.length} onClick={()=>onRun({variables:selected,group})}>{busy?'Generating…':'Generate Table 1'}<span>→</span></button></Panel>}
function PairAnalysis({title,subtitle,a,b,variables,busy,onRun}:{title:string;subtitle:string;a:string;b:string;variables:string[];busy:boolean;onRun:(v:{a:string;b:string})=>void}){const [x,setX]=useState(''),[y,setY]=useState('');return <Panel title={title} subtitle={subtitle}><div className="selection-grid"><SelectBox label={a} value={x} set={setX} variables={variables}/><SelectBox label={b} value={y} set={setY} variables={variables}/></div>{x&&y&&x===y&&<div className="warning">Choose two different variables for this analysis.</div>}<button className="primary" disabled={busy||!x||!y||x===y} onClick={()=>onRun({a:x,b:y})}>{busy?'Running…':'Run analysis'}<span>→</span></button></Panel>}
function SelectBox({label,value,set,variables}:{label:string;value:string;set:(v:string)=>void;variables:string[]}){return <label className="field"><span>{label}</span><select value={value} onChange={e=>set(e.target.value)}><option value="">Choose a variable…</option>{variables.map(v=><option key={v}>{v}</option>)}</select></label>}
function Regression({variables,busy,onRun}:{variables:string[];busy:boolean;onRun:(path:string,c:any)=>void}){const [outcome,setOutcome]=useState(''),[predictors,setPredictors]=useState<string[]>([]),[kind,setKind]=useState('poisson');return <Panel title="Regression" subtitle="Choose an outcome and predictors. Poisson is used for risk-ratio models; logistic returns odds ratios."><div className="selection-grid"><SelectBox label="Outcome" value={outcome} set={setOutcome} variables={variables}/><label className="field"><span>Model</span><select value={kind} onChange={e=>setKind(e.target.value)}><option value="poisson">Poisson / RR</option><option value="logistic">Logistic / OR</option></select></label></div><VariablePicker title="Predictors" variables={variables.filter(v=>v!==outcome)} hint="Select predictors for the model." action="Run regression" busy={busy} onRun={v=>{setPredictors(v);if(outcome)onRun(kind==='poisson'?'/api/v1/analysis/poisson':'/api/v1/analysis/logistic',{outcome,predictors:v})}}/></Panel>}
function Panel({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <section className="panel"><div className="panel-head"><div><h2>{title}</h2><p>{subtitle}</p></div></div>{children}</section>}
function Empty({icon,title,text}:{icon:string;title:string;text:string}){return <div className="empty"><span>{icon}</span><h3>{title}</h3><p>{text}</p></div>}
function Quality({data}:{data:any}){return <Panel title="Data Quality" subtitle="Missingness and data consistency overview.">{data?<pre className="result-pre">{JSON.stringify(data,null,2)}</pre>:<Empty icon="✓" title="No quality report" text="Upload a dataset to generate the quality report."/>}</Panel>}
function Results({result}:{result:ApiResponse|null}){return <Panel title="Results & Export" subtitle="Review the statistical output returned by the analysis engine.">{result?<pre className="result-pre">{JSON.stringify(result,null,2)}</pre>:<Empty icon="↓" title="No results yet" text="Run an analysis to see results here."/>}</Panel>}

createRoot(document.getElementById('root')!).render(<App />)
